Repository minetest-mods/3d_armor, pull requests merged in 2023-10, with the labels that each got.

#116 Add `initial_properties` to armor stand entity
  3d_armor_stand/init.lua
Labels: enhancement

#115 init-cleanup
  3d_armor/README.md
  3d_armor/api.lua
  3d_armor/armor.conf.example
  3d_armor/init.lua
  3d_armor/mod.conf
  3d_armor_ui/init.lua
  settingtypes.txt
Labels: enhancement

#120 Enhance the admin boots (double speed)
  armor_admin/init.lua
Labels: enhancement

#121 Fix ldoc ci
  .ldoc/gendoc.sh
Labels: bug

#122 Remove individual mod LICENSE.txt
  3d_armor/LICENSE.txt
  3d_armor_ip/LICENSE.txt
  3d_armor_sfinv/LICENSE.txt
  3d_armor_stand/LICENSE.txt
  3d_armor_ui/LICENSE.txt
  armor_admin/LICENSE.txt
  armor_bronze/LICENSE.txt
  armor_cactus/LICENSE.txt
  armor_crystal/LICENSE.txt
  armor_diamond/LICENSE.txt
  armor_gold/LICENSE.txt
  armor_mithril/LICENSE.txt
  armor_nether/LICENSE.txt
  armor_steel/LICENSE.txt
  armor_wood/LICENSE.txt
  cc-by-sa-3.0.txt
  lgpl-2.1.md
  shields/LICENSE.txt
  wieldview/LICENSE.txt
Labels: documentation
